# Generated by Django 4.2 on 2026-04-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalwebsite', '0003_user_address_user_contactno_user_dob_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contactno',
            new_name='phone',
        ),
    ]
