# Generated by Django 4.2 on 2026-04-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalwebsite', '0004_rename_contactno_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.URLField(),
        ),
    ]
