# Generated by Django 4.2 on 2026-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalwebsite', '0005_alter_doctors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
