# Generated by Django 4.2 on 2026-05-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalwebsite', '0007_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20),
        ),
    ]
